### ISSUE TITLE
Feeds Fail Safe

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/feeds#11]
Once poet#265 is implemented, the backend will start returning a 503 when it's unable to timestamp a work.

Feeds should catch these errors and try posting the works later.

If a feed fails in any step (profile posting, works posting, licenses posting), poet-feeds should quit processing that particular feed entirely, moving on to the next one.

**Comment by pmosse** [comment]
@lautarodragan I understad this one is done as the related one is done, right?

**Comment by lautarodragan** [comment]
No, the related one was the change in poet-feed-consumer. We still need to change poet-feeds so it catches errors thrown by poet-feed-consumer

**Comment by pmosse** [comment]
Closes with commit: [dd8e32ce3cb140ae52c4951a4f9d78fcbbd1efbf](https://github.com/poetapp/feeds/commit/dd8e32ce3cb140ae52c4951a4f9d78fcbbd1efbf)
