### ISSUE TITLE
Feeds Configurable Delay

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/feeds#8]
Move delay configuration from code to https://github.com/poetapp/feeds-conf

**Comment by pmosse** [comment]
Esto lo estoy haciendo con una configuracion unica de delay para todos (que puede ser un valor o puede dividirse en 3 como habiamos visto), pero no estoy haciendo una configuracion para cada uno de los feeds porque creo que no tiene sentido y complejiza mucho el codigo.
